/**
 * Identity Module for Cert-SDK
 * Handles hardware identity registration and verification
 */

import type { CertSDK } from './index';
import type { SDKResult } from './types';

/**
 * Module for managing CertID hardware identities
 */
export class IdentityModule {
  private sdk: CertSDK;

  constructor(sdk: CertSDK) {
    this.sdk = sdk;
  }

  /**
   * Register a new hardware device identity on Arbitrum L2.
   * @param publicKey - The 64-byte uncompressed X/Y coordinates from the device
   * @param registrationFee - Optional fee to send with the transaction (in wei)
   */
  async registerHardwareIdentity(publicKey: string, registrationFee?: bigint | string): Promise<SDKResult<string>> {
    if (!this.sdk.isConnected()) {
      return { success: false, error: 'SDK not connected. Call autoConnect() first.' };
    }

    try {
      const safeKey = publicKey.startsWith('0x') ? publicKey : '0x' + publicKey;
      const overrides = registrationFee ? { value: registrationFee } : {};
      
      const tx = await this.sdk.contracts.certID.registerHardwareIdentity(safeKey, overrides);
      await tx.wait();
      return { success: true, txHash: tx.hash };
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      return { success: false, error: message };
    }
  }

  /**
   * Verify a WebAuthn biometric signature via Arbitrum Stylus
   * @param msgHash - The hashed challenge data
   * @param signature - The P-256 signature generated by the device's Secure Enclave
   */
  async verifyBiometricLogin(msgHash: string, signature: string): Promise<boolean> {
    try {
      const safeHash = msgHash.startsWith('0x') ? msgHash : '0x' + msgHash;
      const safeSig = signature.startsWith('0x') ? signature : '0x' + signature;

      const isValid = await this.sdk.contracts.certID.verifyBiometricLogin(
        safeHash,
        safeSig
      );

      return isValid;
    } catch (error) {
      console.error('[CertSDK] verifyBiometricLogin failed:', error);
      return false;
    }
  }
}
